### ISSUE TITLE
Set interval for each attempt

### ISSUE THREAD

**Issue by vitorcremonez** [Rocketseat/adonis-bull#10]
I am trying to configure a queue with "attempts" field number.
I need to retry again in my interval configuration time  if job fail, not at once.

As described in official bull documentation. For each new attempt the job is put on delayed mode, but this seems to not working.

![job-lifecycle](https://user-images.githubusercontent.com/22584064/72032337-d4b9ec80-326d-11ea-867b-62bf73b74ee4.png)

How can I configure that?

```javascript
Bull.add(ForgotPasswordMail.key, {
        email: user.email,
        token: user.token
}, {
        delay: 2000,
        attempts: 3
});
```

With this configuration, the delay work until begin processing, after 2000ms the code run 3 times without interval between execution.

**Comment by HigoRibeiro** [comment]
This should work the way you set it up!! 🤔 
I'll try the same test you did

**Comment by kennedyrs** [comment]
I have the same behavior here, any update?

**Comment by ruanitto** [comment]
> I am trying to configure a queue with "attempts" field number.
> I need to retry again in my interval configuration time if job fail, not at once.
> 
> As described in official bull documentation. For each new attempt the job is put on delayed mode, but this seems to not working.
> 
> ![job-lifecycle](https://user-images.githubusercontent.com/22584064/72032337-d4b9ec80-326d-11ea-867b-62bf73b74ee4.png)
> 
> How can I configure that?
> 
> ```js
> Bull.add(ForgotPasswordMail.key, {
>         email: user.email,
>         token: user.token
> }, {
>         delay: 2000,
>         attempts: 3
> });
> ```
> 
> With this configuration, the delay work until begin processing, after 2000ms the code run 3 times without interval between execution.

I solve this with [backoff option](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd)

backoff: number | BackoffOpts; // Backoff setting for automatic retries if the job fails

In my case:
{
      delay: 1500,
      attempts: 20,
      removeOnComplete: true,
      backoff: {
        type: 'exponential',
        delay: 3000
      }
}

A static configuration can also be created inside your job:

 ```
 static get options() {
    return {
      delay: 1500,
      attempts: 20,
      removeOnComplete: true,
      backoff: {
        type: 'exponential',
        delay: 3000
      }
    }
  }
```
