### ISSUE TITLE
Processing multiple jobs

### ISSUE THREAD

**Issue by joaorbrodrigues** [Rocketseat/adonis-bull#14]
Hi!

First of all, thanks for coding this provider. I'm pretty new to development and not all things are clear.

I'm facing the following issue at the moment: 
`Missing process handler for job type 64788854000167`

This happens when I try to add more than one job on the same controller...

How things are set up here:

Under **app/jobs**, I have two classes:
- CreateCustomer
- CreateSubAccount

Basically they call a vendor endpoint to register data...

In **start/jobs.js**, I have the following:

```javascript
module.exports = ['App/Jobs/CreateCustomer', 'App/Jobs/CreateSubAccount']
```

In **config/bull.js**, I have the following:

```javascript
'use strict'

const Env = use('Env')

module.exports = {
  // redis connection
  connection: Env.get('BULL_CONNECTION', 'BULL')
}
```

In **preloads/bull.js**, I have the following:

```javascript
const Bull = use('Rocketseat/Bull')

Bull.process()

// Optionally you can start BullBoard:
Bull.ui()
// http://localhost:9999
```

This is the **server.js**:
```javascript
'use strict'

const { Ignitor } = require('@adonisjs/ignitor')

new Ignitor(require('@adonisjs/fold'))
  .appRoot(__dirname)
  .preLoad('preloads/bull')
  .fireHttpServer()
  .catch(console.error)
```

Under **app/controllers/http**, i have the following controller:

```javascript
'use strict'

const Bull = use('Rocketseat/Bull')
const createCustomerJob = use('App/Jobs/CreateCustomer')
const createSubAccountJob = use('App/Jobs/CreateSubAccount')

class CustomerController {

  async store({
    request,
    response
  }) {

    const customer = {
      email: request.body.email,
      name: request.body.name,
      cpf_cnpj: request.body.cpf_cnpj,
      zip_code: request.body.zip_code,
      number: request.body.number,
      street: request.body.street,
      city: request.body.city,
      state: request.body.state,
      complement: request.body.complement,
      phone_prefix: request.body.phone_prefix,
      phone: request.body.phone
    }

    Bull.add(createCustomerJob.key, customer)
    Bull.add(createSubAccountJob.key, customer.cpf_cnpj)

    return response.status(201).json({
      message: `Job added to queue`
    })

  }

}

module.exports = CustomerController
```

When I was adding only one job, things were working fine, now that I added another job, the second one is throwing the error I mentioned...

Could you please help? Maybe I'm missing something here...

Thanks

**Comment by HigoRibeiro** [comment]
Hi @joaorbrodrigues!! 
Your settings look correct!
I'll try to follow you and see if I find anything!

**Comment by HigoRibeiro** [comment]
@joaorbrodrigues how are your jobs?
I tried to add two jobs and everything went well.

**Comment by joaorbrodrigues** [comment]
Hi @HigoRibeiro ,

Here are the jobs:

```js
const rp = use('request-promise')
const Env = use('Env')

class CreateCustomer {

  static get key() {
    return 'CreateCustomer-key'
  }

  async handle(job) {

    const { data } = job

    try {
      const options = {
        method: 'POST',
        uri: Env.get('URL') + `/customers?api_token=${Env.get('API_KEY')}`,
        body: data,
        json: true
      }

      const result = await rp(options)

      return result

    } catch (error) {
      throw new Error('Something went wrong')
    }
  }

}

module.exports = CreateCustomer
```

```js

const rp = use('request-promise')
const Env = use('Env')

class CreateSubAccount {

  static get key() {
    return 'CreateSubAccount-key'
  }

  async handle(job) {

    const { data } = job

    try {
      const options = {
        method: 'POST',
        uri: Env.get('IUGU_URL') + `/marketplace/create_account?api_token=${Env.get('API_KEY')}`,
        body: { name: data },
        json: true
      }

      const result = await rp(options)
      return result

    } catch (error) {
      throw new Error('Something went wrong')
    }
  }

}

module.exports = CreateSubAccount

```

Thanks for the support so far

**Comment by pellizzetti** [comment]
Thanks for the detailed issue report @joaorbrodrigues.

@HigoRibeiro IIRC, this is related to running multiple jobs without a [named processor](https://github.com/Rocketseat/adonis-bull/blob/master/src/Queue.js#L151). Take a look at this [issue](https://github.com/OptimalBits/bull/issues/1334) for additional context.

**Comment by HigoRibeiro** [comment]
@joaorbrodrigues thanks!
Looking at the bull's documentation, I realized that the `data` needs to come in the form of an object. And in your code, when you call work `createSubAccountJob` you pass the `data` as a string and there is a possibility that it is null which generates this error. Can you verify that?

**Comment by joaorbrodrigues** [comment]
@pellizzetti , based on the error I was getting, this is one of the issues I checked before opening this one.

@HigoRibeiro that was the error! Thank you so much for the analysis!

I would never have guessed that based on the error I was getting.

Keep up the amazing work.
