### ISSUE TITLE
Use Mail (readme)

### ISSUE THREAD

**Issue by brunoesposito** [Rocketseat/adonis-bull#18]
Acredito ter achado um possível erro na documentação. Nesse [ponto do Readme](https://github.com/Rocketseat/adonis-bull#creating-your-job) está informando que deverá ser importado o Mail através de uma const no topo do arquivo. Só que aqui pra mim aparece o seguinte erro...

```
Error: Cannot find module 'Adonis/Src/View'
```
Então o seguinte ajuste foi feito aqui **no meu código**:

```
async handle(job) {
        const Mail = use('Mail');
        const { data } = job;
....
```

E o server reiniciou normalmente. Confere?

**Comment by brunoesposito** [comment]
eu inclui o:

```
const providers = [
  '@adonisjs/framework/providers/ViewProvider'
]
```

e resolveu o problema!

**Comment by HigoRibeiro** [comment]
Fala @brunoesposito só para dar o meu parecer, ocorre que o `Mail` depende da `View` para ele gerar o `hmtl` de acordo com o arquivo `edge`.
No exemplo era apenas uma ilustração de como pode ser chamado.

Muito obrigado pela contribuição.
Abraços
