### ISSUE TITLE
Dúvidas de uso dos Jobs

### ISSUE THREAD

**Issue by kennedyrs** [Rocketseat/adonis-bull#19]
Eu tenho uma dúvida quanto ao Bull, dentro do método handle, como eu digo que algo não deu certo?

Por exemplo, dependendo da resposta de uma API, quero que a fila tente executar a ação novamente mais tarde.

```js
async handle(job) {
    const { data } = job; 

   ...

    return data;
  }
```

Seria só lançar uma Exception?

```js
throw new Error('Deu erro...')
```

**Comment by HigoRibeiro** [comment]
Fala @kennedyrs !
Isso mesmo, lança exceção que é a maneira de dizer que o serviço não deu certo!

**Comment by kennedyrs** [comment]
Outra dúvida, qual seria a melhor estratégia para acionar um job assim que a aplicação iniciar?

`Bull.add(Job.key, {
  delay: 6000,
  attempts: 3,
  repeat: {
    cron: '0 */6 * * *'
  }
})`

**Comment by jpedroschmitz** [comment]
Hey @kennedyrs, this issue was closed because it was not following the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

**Comment by RicardoPBarbosa** [comment]
> Cria um ServiceProvider com `adonis make:provider SeuProvider` e roda chame ele no método *_boot_ do provider.
> 
> Ah, tem que registrar o provider no array `providers` do `start/app.js`
> 
> ```js
> const path = require('path')
> 
> const providers = [
>   ...
>   '@rocketseat/adonis-bull/providers/Bull',
>   path.join(__dirname, '..', 'providers', 'SeuProvider'),
> ]
> ```

Estou tentanto fazer isto mas no Provider em que função corro os ```Bull.add()```? Tentei em ```register```, ```boot``` mas não estou conseguindo importar o Bull do tipo ```const Bull = this.app.use('Rocketseat/Bull');``` dá sempre ```Bull.add is not a function```.

Exemplo:
```javascript
boot() {
    const Bull = this.app.use('Rocketseat/Bull');
    const Job = this.app.use('App/Jobs/Job');
    Bull.add(Job.key, { attempts: 3, repeat: { cron: '0 0 * * *' } });
}
```
