### ISSUE TITLE
Repeat Cron

### ISSUE THREAD

**Issue by erikjose** [Rocketseat/adonis-bull#21]
Para rodar o job todos os dias as 05:30 da manhã, o que devo fazer?

**Comment by ruanitto** [comment]
Você pode usar o Advanced Jobs:
https://github.com/Rocketseat/adonis-bull#advanced-jobs

Usando o cron 30 5 * * * *

Bull.add(key, data, {
  repeat: {
    cron: "30 5 * * * *"
  }
});

**Comment by HigoRibeiro** [comment]
Hey, I will close this issue for lack of current interactions. Feel free to open it again if necessary.

**Comment by jpedroschmitz** [comment]
Hey @erikjose, while contributing or interacting in any way in this project, refrain from using any language other than English. I recommend you take a look at the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language) 💜
