### ISSUE TITLE
Warning: Adonis has detected an unhandled promise rejection

### ISSUE THREAD

**Issue by Heitorh3** [Rocketseat/adonis-bull#22]
Adonis esta laçando esse warning quando iniciado.
WARNING: Adonis has detected an unhandled promise rejection, which may cause undesired behavior in production. To stop this warning, use catch() on promises or wrap await calls inside try/catch.

Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by HigoRibeiro** [comment]
Fala @Heitorh3 como está seu arquivo `config/bull.js`? Está ligado o `redis` na sua máquina?

**Comment by rodrigorz** [comment]
Estou obtendo esse mesmo erro, porém estou utilizando docker e acontece somente quando executo os testes do adonis.

Quando executo a aplicação, fazendo a requisição pelo Postman, funciona normalmente.

Por que será que nos testes da esse problema?

**Comment by HigoRibeiro** [comment]
Fala @rodrigorz , como está seu arquivo `.env.testing`?

Quando você executa o test está com o docker ligado normalmentE?

**Comment by rodrigorz** [comment]
@HigoRibeiro achei o problema.

Como o redis está em um container e a API em outro, os testes precisam ser executados de dentro do container da API (eu estava executando da minha máquina local). Por isso ele não conectava, já que eu passava o nome do container do redis como host.

Porém agora estou enfrentando outro erro:
`1. it should send an email with reset password instructions
  Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at Test._parseError (/home/node/app/node_modules/japa/src/Test.js:109:16)
    at /home/node/app/node_modules/japa/src/Test.js:195:21`.

Vou ver se consigo alterar o timeout desse único teste.

**Comment by rodrigorz** [comment]
> @HigoRibeiro achei o problema.
> 
> Como o redis está em um container e a API em outro, os testes precisam ser executados de dentro do container da API (eu estava executando da minha máquina local). Por isso ele não conectava, já que eu passava o nome do container do redis como host.
> 
> Porém agora estou enfrentando outro erro:
> `1. it should send an email with reset password instructions Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves. at Test._parseError (/home/node/app/node_modules/japa/src/Test.js:109:16) at /home/node/app/node_modules/japa/src/Test.js:195:21`.
> 
> Vou ver se consigo alterar o timeout desse único teste.

Resolvido! Apenas aumentando o timeout do teste.
