### ISSUE TITLE
Is adonis-bull working with Adonis V5 ?

### ISSUE THREAD

**Issue by ouraios** [Rocketseat/adonis-bull#26]
I'd like to start a project with Adonis V5 but i'd like to know if adonis-bull work with this version of adonis ?
Thanks in advance !

**Comment by ymoreiratiti** [comment]
+1

**Comment by HigoRibeiro** [comment]
Hi @ouraios , but the adonis-bull doesn’t work with Adonis V5 yet, but I want to work on that feature soon.

**Comment by zulfi007** [comment]
+1

**Comment by ouraios** [comment]
Cant wait @HigoRibeiro ! That would be amazing !

**Comment by RodolfoSilva** [comment]
I started a PR to add support for Adonis 5, take a look # 39

**Comment by RodolfoSilva** [comment]
I started a PR to add support for Adonis 5, take a look #39

**Comment by detygon** [comment]
That's the missing piece for me. Can't wait for the PR to get merged. Good job @RodolfoSilva and thanks.

**Comment by RodolfoSilva** [comment]
Thanks @detygon. I'm waiting for a review from @HigoRibeiro or @diego3g.

**Comment by mxthevs** [comment]
Looking forward to the V5 support as well

**Comment by HigoRibeiro** [comment]
This issue will be closed to be followed in the #50
