### ISSUE TITLE
mudar ip de host do redis

### ISSUE THREAD

**Issue by evandrogrm** [Rocketseat/adonis-bull#3]
Olá pessoal, boa tarde!
Eu to com o problema de não conseguir configurar o redis para este provider. Está tentando fazer uma conexão para o redis 127.0.0.1 6379, sendo que no arquivo bull.js dentro do config as variaveis de ambiente coloquei outro endereço, tem como alterar?
![Screenshot_173](https://user-images.githubusercontent.com/6799983/71121228-db000000-21bc-11ea-9eac-eda86b68e3fe.png)
![Screenshot_174](https://user-images.githubusercontent.com/6799983/71121282-f23eed80-21bc-11ea-9aef-af23e267fbf3.png)
![Screenshot_175](https://user-images.githubusercontent.com/6799983/71121330-113d7f80-21bd-11ea-8844-5db66bb14ca2.png)

**Comment by HigoRibeiro** [comment]
Fala Evandro!

Na verdade você deve especificar dentro do `config/bull.js`, qual configuração do `config/redis.js` ele vai utilizar, então se no arquivo `config/redis.js` você tem a seguinte configuração:
```js
const Env = use('Env');

module.exports = {
  connection: Env.get('REDIS_CONNECTION', 'local'),
  local: {
    host: '127.0.0.1',
    port: 6379,
    password: null,
    db: 0,
    keyPrefix: '',
  },

  bull: {
    host: Env.get('REDIS_HOST', '127.0.0.1'),
    port: Env.get('REDIS_PORT', '6379'),
    password: Env.get('REDIS_PASSWORD', null),
    db: 0,
    keyPrefix: '',
  },
  cluster: {
    clusters: [
      {
        host: '127.0.0.1',
        port: 6379,
        password: null,
        db: 0,
      },
      {
        host: '127.0.0.1',
        port: 6380,
        password: null,
        db: 0,
      },
    ],
  },
};
```

Você tem 3 opções de conexão: `local`, `bull` e `cluster`.

Na `config/bull.js` você define qual delas você usará para o seu `bull`.
```js
module.exports = {
  connection: 'bull',
};
```

**Comment by evandrogrm** [comment]
Descobri o que tava ocorrendo, eu não usava a porta padrão 6379, utilizo a porta 6380 por ter conflito de portas. Porém quando é utilizado no docker-compose `ports: - "6380:6380"` não basta, não é possível fazer conexão ao banco redis. Para isso é necessário seguir o exemplo desse maravilhoso comentário que me salvou:
https://github.com/luin/ioredis/issues/763#issuecomment-451041838

```
redis:
    image: 'redis:alpine'
    container_name: redis
    command: ["redis-server", "--bind", "redis", "--port", "6380"]
    ports:
      - "6380:6380"
```

Valeu pela ajuda @HigoRibeiro

**Comment by jpedroschmitz** [comment]
Hey @evandrogrm, while contributing or interacting in any way in this project, refrain from using any language other than English. I recommend you take a look at the guidelines [described here](https://github.com/Rocketseat/adonis-bull/blob/master/.github/CONTRIBUTING.md#language) 💜
