### ISSUE TITLE
How to test e-mail sending job?

### ISSUE THREAD

**Issue by lamana-team** [Rocketseat/adonis-bull#30]
Hello friends! I am trying to test the sending of e-mails that is being done within a Job.

The problem I found was that the Mail.fake () functionality does not work when the email is fired from within the Job. It works if the e-mail triggered from a Controller for example.

Do you have any idea how I can get around this?

**Comment by lamana-team** [comment]
I have been working on this problem for a few hours and although I have not been able to find a solution, however I managed to do something paleative.

What I did was create a condition within the control based on the environment. If the variable NODE_ENV is equal to 'testing' I send the email inside the controller instead of running the JOB.

In this case, considering that the job is exclusively for sending an email and has no other logic involved, I think everything is fine. But I still think there is a better way.

**Comment by HigoRibeiro** [comment]
Hi @lamana-team unfortunately this provider is not prepared to work cool with tests, so you need to add a palliative strategy.

When running your tests you shouldn't use the bull as production, I guess that's why what your job is sending the e-mail.

So, what can you do is make a fake provider like below:
```js
// test/mocks/BullMock.js
class BullMock {
  constructor () {
    this.reset()
  }

  call (...args) {
    const [funcName, ...rest] = args
    this.spy.calls.push({ funcName, args: rest, fail: this.fail })
    this.spy.called = true

    if (this.fail) {
      throw new Error(this.fail)
    }
  }

  makeFail (err) {
    this.fail = typeof err === 'string' ? err : 'error'
  }

  clearFail () {
    this.fail = null
  }

  async add (...args) {
    this.call('add', ...args)
  }

  async schedule(...args) {
    this.call('schedule', ...args)
  }

  reset () {
    this.spy = {
      calls: [],
      called: false,
      fail: null
    }
  }
}

module.exports = new BullMock()
```

Then, inside the **vowfile**:
```js
const ace = require('@adonisjs/ace')
const { ioc } = require('@adonisjs/fold')
const BullMock = require('./test/mocks/BullMock')

ioc.singletonFake('Bull', () => BullMock)
```

Now, when you call a test actually you'll use the mock instead of the **RealProvider**.

You can know if your job was called on your test file:
```js
const Bull = use('Bull') // It's the mock.

test('my awesome test', async ({ assert }) => {
  // ...
  
 assert.equal('add', Bull.spy.calls[0].funcName)
 assert.isTrue(Bull.spy.called)
});
```

You should test your job separate as unit test:
```js
const AwesomeJob = use('App/Jobs/AwesomeJob')
const Mail = use('Mail')

test('my awesome test', async ({ assert }) => {
  Mail.fake()

  const job = new AwesomeJob()

  await job.handle({ data: myData })

  // my assertion

  Mail.restote()
});
```

That's it!

**Comment by HigoRibeiro** [comment]
Hey, I will close this issue because is resolved.

**Comment by Agilulfo1820** [comment]
I did same but it doesn't work on my Adonis v4. 
I have a job launched by a controller. I'm testing the endpoint and I want to be sure that the job was launched.

@HigoRibeiro  I set up everything as you said but my actual job is starting and Bull.spy is always `undefined`
