### ISSUE TITLE
Command to generate job class

### ISSUE THREAD

**Issue by TNkemdilim** [Rocketseat/adonis-bull#35]
I believe it'll be a good addition if an ace command existed to generate a job file. 

E.g.: `adonis make:job SendEmail` creates a `app/Jobs/SendEmail.js` from an existing template.

**Comment by HigoRibeiro** [comment]
We will implement this!! :heart:

**Comment by jpedroschmitz** [comment]
Hey @TNkemdilim, we have added a make command for the next version of Adonis Bull, that adds support for Adonis v5. 

You can create jobs files by running `node ace make:job <name>` on the project folder.

To know more about the support for Adonis v5, [click here](https://github.com/Rocketseat/adonis-bull/tree/alpha).

**Comment by TNkemdilim** [comment]
That's awesome. Thanks for the update.
