### ISSUE TITLE
Need to reset statistics from board

### ISSUE THREAD

**Issue by wemersonrv** [Rocketseat/adonis-bull#36]
Good night.

Where are stored the data showed on the job statistics displayed on Bull Dashboard? 

Need to clear them here but don't found!

**Comment by wemersonrv** [comment]
Hello? Is this package died because there are no answers after several months???

**Comment by fhugoduarte** [comment]
Hey @wemersonrv , forgiveness for the delay :disappointed: 

adonis-bull use the [bull-board](https://github.com/vcapretz/bull-board) package, it fetches this information from the queue, that is, it will be stored in redis. The bull-board offers the options to clean some jobs.

We're working on a new version compatible with adonis5 and we will update the bull-board.

I hope it was useful.

**Comment by jpedroschmitz** [comment]
Hey @wemersonrv, we have updated the `bull-board` package to the latest version, where it is now possible to clear all completed/failed jobs or delete specific ones. That's the reason I'm closing this issue, if you have any questions, let me know.

![shot](https://user-images.githubusercontent.com/26466516/106032539-5a921b00-60af-11eb-9cf5-84d4966782a3.png)

**Comment by wemersonrv** [comment]
Hello,

I'm still on the version **0.2.3** due to compatibility issues on my project, because i don't update it to adonis 5 yet.

Well i'm having an annoying issue when it gets a large amount of jobs list on board (completed, failed, etc)... it gets a lot of memory and is going to use a lot of swap. Last server i've checked it has about 50K completed jobs on list and it costs me a lot of memory, and after clean the jobs; it frees a lot of memory.

So, there is some method that i need to call from my project to empty old messages so i put it in a scheduled job to keep only a list with last month jobs?

**Comment by wemersonrv** [comment]
Hello, updating... The dashboard is giving me the error `ERR_CONNECTION_REFUSED`, but just the dashboard has this issue. It works fine and the Jobs are working.

OS: **Ubuntu Server 20.04**
Nodejs: **v12.22.4**
