### ISSUE TITLE
How can i update a job progress information ?

### ISSUE THREAD

**Issue by wemersonrv** [Rocketseat/adonis-bull#37]
Hello, i have some jobs that are a bit slow and need to show the running progress.

So, How can i update a job progress information ?

**Comment by capoia** [comment]
@wemersonrv you can tell me how?

**Comment by wemersonrv** [comment]
> @wemersonrv you can tell me how?

@capoia just call the `updateProgress(...)` method passing the percentage of progress as an argument. See an example:

```js
 await job.updateProgress(10.33) // 10.33% 
 ```

As the adonis-bull is a package to wrap for BullMQ, so i've check the bullmq docs and found a bunch of info. See here: https://api.docs.bullmq.io/classes/Job.html#updateProgress.
