### ISSUE TITLE
Is Project Stable?

### ISSUE THREAD

**Issue by TNkemdilim** [Rocketseat/adonis-bull#4]
Thanks for such a great library.

Considering that kue is no longer maintained, bull serves as a better alternative.

I'll love to find out if this library is currently stable for production?

**Comment by ebnersilva** [comment]
Hi
I am using this library and so far no problem.

**Comment by TNkemdilim** [comment]
Great @ebnersilva. 

Also, is there some kind of support for `auto-retry` and `timeout`?

**Comment by ebnersilva** [comment]
Yes, follow the link: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

**Comment by TNkemdilim** [comment]
Thanks.
