### ISSUE TITLE
How to customize url of bull board?

### ISSUE THREAD

**Issue by cheesepaulo** [Rocketseat/adonis-bull#42]
const Bull = use("Rocketseat/Bull");

Bull.process()
  // Optionally you can start BullBoard:
  **.ui(9999); // http://localhost:9999  // I change this line to ex: admin/jobs ..... app fails**
// You don't need to specify the port, the default number is 9999

I need to protect this route.

**Comment by LeCoupa** [comment]
It looks like the `ui()` function only accepts a port number. Why don't you use something like Nginx for this?

**Comment by fhugoduarte** [comment]
Hey @cheesepaulo , I will close this issue for lack of current interactions. Feel free to open it again if necessary.
