### ISSUE TITLE
Adonis V5 migration

### ISSUE THREAD

**Issue by HigoRibeiro** [Rocketseat/adonis-bull#50]
We're working on integration with adonis v5.

### :construction:  Roadmap 
 - [X] Command improvement
 - [X] Bull Board upgrade
 - [X] Fix schedule method
 - [X] README improvement
 - [X] Tests adjustments (#57)
 

Special thanks @RodolfoSilva for initializing the implementation in PR #39

**Comment by ruanitto** [comment]
Tava fazendo alguns testes já com o pacote, não sei se vocês já realizaram o ajuste, caso sim pode desconsiderar.

Mas ele dá um erro com a conexão ao redis, pq nas linhas 40 e 116, ele passa o objeto BullConnectionContract inteiro, e não apenas a configuração definida.

**Comment by fhugoduarte** [comment]
Hi @ruanitto :hugs: 

We are making some changes, but could you give us more information about the error?

**Comment by fhugoduarte** [comment]
> Tava fazendo alguns testes já com o pacote, não sei se vocês já realizaram o ajuste, caso sim pode desconsiderar.
> 
> Mas ele dá um erro com a conexão ao redis, pq nas linhas 40 e 116, ele passa o objeto BullConnectionContract inteiro, e não apenas a configuração definida.

Hi @ruanitto hugs

We are making some changes, but could you give us more information about the error?

**Comment by zulfi007** [comment]
Finally🤓

**Comment by ashokgelal** [comment]
> Tava fazendo alguns testes já com o pacote, não sei se vocês já realizaram o ajuste, caso sim pode desconsiderar.
> 
> Mas ele dá um erro com a conexão ao redis, pq nas linhas 40 e 116, ele passa o objeto BullConnectionContract inteiro, e não apenas a configuração definida.

Sorry I don't talk Portuguese and I'm just trying to help :)

I don't know if this is related but the instructions in the README file is wrong about how to configure the connection. I've updated the README in fork so feel free to consult it: https://github.com/ashokgelal/adonis-bull

Basically, there are two steps missing/incomplete in the README:
1. Setup: `node ace invoke @ashokgelal/adonis-bull`
2. `config/bull.ts`:
```ts
import Env from '@ioc:Adonis/Core/Env'
import { BullConfig } from '@ioc:Rocketseat/Bull'


const bullConfig: BullConfig = {
  connection: Env.get('BULL_CONNECTION', 'bull'),
  connections: {
    bull: {
  	  host: Env.get('BULL_REDIS_HOST'),
  	  port: Env.get('BULL_REDIS_PORT'),
  	  password: Env.get('BULL_REDIS_PASSWORD', ''),
  	  db: 0,
  	  keyPrefix: '',
    },
  }
}

export default bullConfig
```

Happy to help you on the Adonis discord server if you need more help.

**Comment by fhugoduarte** [comment]
> > Tava fazendo alguns testes já com o pacote, não sei se vocês já realizaram o ajuste, caso sim pode desconsiderar.
> > Mas ele dá um erro com a conexão ao redis, pq nas linhas 40 e 116, ele passa o objeto BullConnectionContract inteiro, e não apenas a configuração definida.
> 
> Sorry I don't talk Portuguese and I'm just trying to help :)
> 
> I don't know if this is related but some of the instructions in the README file is wrong/incomplete about how to configure the connection. I've updated the README in fork so feel free to consult it: https://github.com/ashokgelal/adonis-bull
> 
> Basically, there are two steps missing/incomplete in the README:
> 
> 1. Setup: `node ace invoke @ashokgelal/adonis-bull`
> 2. `config/bull.ts`:
> 
> ```ts
> import Env from '@ioc:Adonis/Core/Env'
> import { BullConfig } from '@ioc:Rocketseat/Bull'
> 
> 
> const bullConfig: BullConfig = {
>   connection: Env.get('BULL_CONNECTION', 'bull'),
>   connections: {
>     bull: {
>   	  host: Env.get('BULL_REDIS_HOST'),
>   	  port: Env.get('BULL_REDIS_PORT'),
>   	  password: Env.get('BULL_REDIS_PASSWORD', ''),
>   	  db: 0,
>   	  keyPrefix: '',
>     },
>   }
> }
> 
> export default bullConfig
> ```
> 
> Happy to help you on the Adonis discord server if you need more help.

No problem, we're talking in English by default, as this package isn't only used by people who speak Portuguese.

Thx you for your report, but we added all the necessary setup for the bull configuration in the `invoke` command. Then with the invoke command your project will be ready to work with jobs that will be created with the `make:job` command. We're done with that.

**Comment by ruanitto** [comment]
> > Tava fazendo alguns testes já com o pacote, não sei se vocês já realizaram o ajuste, caso sim pode desconsiderar.
> > Mas ele dá um erro com a conexão ao redis, pq nas linhas 40 e 116, ele passa o objeto BullConnectionContract inteiro, e não apenas a configuração definida.
> 
> Sorry I don't talk Portuguese and I'm just trying to help :)
> 
> I don't know if this is related but some of the instructions in the README file is wrong/incomplete about how to configure the connection. I've updated the README in fork so feel free to consult it: https://github.com/ashokgelal/adonis-bull
> 
> Basically, there are two steps missing/incomplete in the README:
> 
> 1. Setup: `node ace invoke @ashokgelal/adonis-bull`
> 2. `config/bull.ts`:
> 
> ```ts
> import Env from '@ioc:Adonis/Core/Env'
> import { BullConfig } from '@ioc:Rocketseat/Bull'
> 
> 
> const bullConfig: BullConfig = {
>   connection: Env.get('BULL_CONNECTION', 'bull'),
>   connections: {
>     bull: {
>   	  host: Env.get('BULL_REDIS_HOST'),
>   	  port: Env.get('BULL_REDIS_PORT'),
>   	  password: Env.get('BULL_REDIS_PASSWORD', ''),
>   	  db: 0,
>   	  keyPrefix: '',
>     },
>   }
> }
> 
> export default bullConfig
> ```
> 
> Happy to help you on the Adonis discord server if you need more help.

Sorry, my English is not very good, I ended up using the google translator but at the time it was kind of curled up and I ended up writing in Portuguese.
First of all, thank you very much for teaching all of you with the package, I think it is sensational.

I did all the configuration really according to your repository, but the connection to the redis failed, I performed the debug, and in the BullManager.ts file, there was an error when passing the connections to Bull, but it has already been fixed.
Thanks :)

**Comment by zulfi007** [comment]
My suggestion is keep migration in alpha branch and   in typescript as adonis v5 is mostly in ts.
Readme file also needs rewrite as per new rules.

**Comment by jpedroschmitz** [comment]
Hey @zulfi007, we will do that. The documentation and code for version 5 will be on a separated branch (named `alpha`) while Adonis 5 is still in beta. After that, we will merge it on master and will be the default.

**Comment by jpedroschmitz** [comment]
Hey guys, the support for version 5 was officially released 🎉 

It is a premajor, and may contain bugs, but we encourage you to use it on your projects and report any problem you may have.

To get started with it, you can install it with NPM or Yarn:

```sh
yarn add @rocketseat/adonis-bull@alpha
# or
npm install @rocketseat/adonis-bull@alpha
```

After installing it, run `node ace invoke @rocketseat/adonis-bull`, choose a start option and you're ready to go ⚡️

You can find the complete [documentation here](https://github.com/Rocketseat/adonis-bull/tree/alpha#readme), and if you want to add more examples or guides, don't hesitate to open a PR 💜

**Comment by LeCoupa** [comment]
Great @jpedroschmitz! Will install it tomorrow :)
