### ISSUE TITLE
Show bull-board on a custom route [V5]

### ISSUE THREAD

**Issue by rodrigorz** [Rocketseat/adonis-bull#63]
**What would you like to be added**:

The bull-board package has a config to show the dashboard on a custom route ([here](https://github.com/vcapretz/bull-board), inside Hello World section) using express, and i think the adonis-bull can have the same functionality.

**Why is this needed**:

I'll need this, because the Admin User of my system will need to retry the failed jobs if necessary.

**Is your enhancement request related to a problem? Please describe.**

The only problem is that the Admin User has no control over the jobs.

**Additional context**

Here is an image from the bull-board config that i said.
![image](https://user-images.githubusercontent.com/17011258/106191266-681bd380-6189-11eb-8cfe-658908dfa859.png)

Is it possible? Or has a better way to do it?

ps: Thanks for the Adonis V5 support!!

**Comment by HigoRibeiro** [comment]
Hi @rodrigorz !!

I checked this question and tried and several ways to customize the route, but without success. I have come to the conclusion that it is not possible.

A suggestion is to configure your web server to handle this.

Thanks.

**Comment by rodrigorz** [comment]
Hi @HigoRibeiro

I'll try some ideas and if it works out I'll come back here to show.

Thanks.

**Comment by technoknol** [comment]
Anyone got any luck?
