### ISSUE TITLE
Missing step at provider configuration?

### ISSUE THREAD

**Issue by pellizzetti** [Rocketseat/adonis-bull#7]
@HigoRibeiro 

Taking a look at this [line][l21] we can see that all configuration from this provider come from `config/redis.js`.

Since this is missing in the `README` and I have nowhere near your experience with AdonisJS, I'll ask:

Is this step implicit? I know this file is created when we install the official Redis provider. Is this something that is expected of those who use this provider to be aware of?

Should this be added to the documentation?

Or would be better to move all provider settings to the `config/bull.js` file?

[l21]: https://github.com/Rocketseat/adonis-bull/blob/master/src/Queue.js#L21

**Comment by HigoRibeiro** [comment]
@pellizzetti 

Actually, it's not necessary we install the Redis provider to use our provider, it's necessary that the `config/redis.js` file exists to indicate which `redis` configuration we'll use.

I agree to move all provider settings to the `config/bull.js` file and maybe add on `job class` a connection method for when we need to use specific connection setting.

**Comment by pellizzetti** [comment]
#13 fixes this. 😄
