### ISSUE TITLE
Dúvida sobre o Bull

### ISSUE THREAD

**Issue by arthur-rs** [Rocketseat/adonis-bull#99]
### Oi, tudo bem?

Bem, estava com uma dúvida, os jobs são executados 1 por 1 ou vários de uma vez. Para manter a segurança da minha aplicação eu realmente preciso que seja executado 1 por 1, ele já vem no padrão assim? Ou preciso configurar alguma coisa?

Pq preciso disso? Minha aplicação irá processar transações financeiras reais, para uma melhor segurança e evitar fraudes, preciso que essas transações seja vem feito 1 por 1.

**Comment by ruanitto** [comment]
Hi Arthur,

The default is only 1 concurrency Job by queue, check default option in package for v4:
https://github.com/Rocketseat/adonis-bull/blob/b14fe6207ff9f4320bf76f57766994edd46516cb/src/Queue.js#L55

And in package for v5:

https://github.com/Rocketseat/adonis-bull/blob/d5397350d328f8d14e08feb9da5247c981848f97/src/BullManager.ts#L151
